mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
  #有configuration了，就不能有mybatis-config.xml了，否则报错
  #驼峰命名法
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nk-bbs?&serverTimezone=GMT%2B8
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
